name: Deploy
on:
  push:
    branches:
      - release
      - main
jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Install Dependencies
        run: sudo apt update && sudo apt install --yes --no-install-recommends libboost-system-dev libboost-program-options-dev
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --parallel
      - name: Debian Package
        run: cpack -G DEB --config build/CPackConfig.cmake
      - name: RPM Package
        run: cpack -G RPM --config build/CPackConfig.cmake
