name: Deploy
on:
  push:
    tags:
      - v*
jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    steps:
      - name: Install Dependencies
        run: sudo apt update && sudo apt install --yes --no-install-recommends libboost-system-dev libboost-program-options-dev
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --parallel
      - name: Generate Debian Package
        run: cpack -G DEB --config build/CPackConfig.cmake
      - name: Generate RPM Package
        run: cpack -G RPM --config build/CPackConfig.cmake
      - name: Generate ZIP Package
        run: cpack -G ZIP --config build/CPackConfig.cmake
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      - name: Find RPM Package
        run: |
          PACKAGE_PATH=$(find build/packages -type f -name "*.rpm")"
          PACKAGE_NAME="$(basename "$PACKAGE_PATH")"
          echo "PACKAGE_PATH=$PACKAGE_PATH" >> $GITHUB_ENV
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
      - name: Upload Package
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.PACKAGE_PATH }}
          asset_name: ${{ env.PACKAGE_NAME }}
          asset_content_type: application/x-rpm
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
